CREATE TABLE MEMBER_COPY AS SELECT * FROM CS306.MEMBER;
CREATE TABLE SUBIN_SUBSCRIPTION_COPY AS SELECT * FROM CS306.SUBIN_SUBSCRIPTION;

-- 1st

-- Before adding indexes

SET profiling = 1;

SELECT *

FROM MEMBER_COPY
JOIN SUBIN_SUBSCRIPTION_COPY ON MEMBER_COPY.MEM_ID = SUBIN_SUBSCRIPTION_COPY.MEM_ID
WHERE MEMBER_COPY.MEM_DATE > 2008
AND SUBIN_SUBSCRIPTION_COPY.SUB_PRICE > 250

LIMIT 1000000;

SHOW PROFILE;


-- Adding indexes
CREATE INDEX idx_columna ON MEMBER_COPY(MEM_DATE);
CREATE INDEX idx_columnb ON SUBIN_SUBSCRIPTION_COPY(SUB_PRICE);

-- After adding indexes

SET profiling = 1;

SELECT *
FROM MEMBER_COPY
JOIN SUBIN_SUBSCRIPTION_COPY ON MEMBER_COPY.MEM_ID = SUBIN_SUBSCRIPTION_COPY.MEM_ID
WHERE MEMBER_COPY.MEM_DATE > 2008
AND SUBIN_SUBSCRIPTION_COPY.SUB_PRICE > 250
LIMIT 1000000;

SHOW PROFILE;


# ---------------------------------------------------------------------------------------------------------------------------------


-- 2nd

-- Before adding indexes

SET profiling = 1;

SELECT *
FROM MEMBER_COPY
JOIN SUBIN_SUBSCRIPTION_COPY ON MEMBER_COPY.MEM_ID = SUBIN_SUBSCRIPTION_COPY.MEM_ID
WHERE MEMBER_COPY.MEM_FIRSTNAME LIKE '%at%'
OR MEMBER_COPY.MEM_FIRSTNAME LIKE '%te%'
OR MEMBER_COPY.MEM_FIRSTNAME LIKE '%an%'
AND SUBIN_SUBSCRIPTION_COPY.SUB_TYPE = 'VIP'
LIMIT 1000000;

SHOW PROFILE;

-- Adding indexes
CREATE INDEX idx_MEM_FIRSTNAME ON MEMBER_COPY(MEM_FIRSTNAME);
CREATE INDEX idx_SUB_TYPE ON SUBIN_SUBSCRIPTION_COPY(SUB_TYPE);

-- After adding indexes

SET profiling = 1;

SELECT *
FROM MEMBER_COPY
JOIN SUBIN_SUBSCRIPTION_COPY ON MEMBER_COPY.MEM_ID = SUBIN_SUBSCRIPTION_COPY.MEM_ID
WHERE MEMBER_COPY.MEM_FIRSTNAME LIKE '%at%'
OR MEMBER_COPY.MEM_FIRSTNAME LIKE '%te%'
OR MEMBER_COPY.MEM_FIRSTNAME LIKE '%an%'
AND SUBIN_SUBSCRIPTION_COPY.SUB_TYPE = 'VIP'
LIMIT 1000000;

SHOW PROFILE;

